BOT_TOKEN = "{BOT_TOKEN}"
DIRECT_LINE_SECRET = "{DIRECT_LINE_SECRET}"
ADMIN_USER_NAMES = ["deeplearninggod"]
QNA_MAKER_ENDPOINT = "https://ukraine-lang.cognitiveservices.azure.com/"
QNA_SUBSCRIPTION_KEY = "{YOUR_SUBSCRIPTION_KEY}"
KNOWLEDGEBASE_ID = "Test"
